name: echo-issues
on: [issues]
jobs:
    print-issues:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Issue title: ${{github.event.issue.title}}"
                echo "Issue body: ${{github.event.issue.body}}"
