name: workflow_parallel
on: [push]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: pull-code
              uses: actions/checkout@v3
            - name: install-depend
              run: npm install
            - name: run-lint
              run: npm run lint
    test:
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: test-app
              run: npm run test
    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - run: npm run build