name: running vite app
on: [push]
jobs:
    run-app:
        runs-on: ubuntu-latest
        steps:
            - name: pull-code
              uses: actions/checkout@v3
            - name: lint
              run: npm run build
            - name: test
              run: npm run test
            - name: build
              run: npm run build
        