name: Deployment Exercise parallel
on: [push]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: pull-code
              uses: actions/checkout@v3
            - name: install-depend
              run: npm install
            - name: run-lint
              run: npm run lint
    test:
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - uses: actions/checkout@v3
            - run: npm ci
            - name: test-app
              run: npm run test
    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - uses: actions/checkout@v3
            - run: npm install
            - run: npm run build
            - name: Deploy code
              run: echo "Deploying ..."